name: Combined Pipeline

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:    

  # Step 1: Run tfscan pipeline (Quality checks)
  # run-tfscan:
  #   uses: ./.github/workflows/tfscan.yml
  #   with:
  #     workingDirectory: modules/resourcegroup

  # Step 2: Deploy using deploy.yml if scanning passes
  run-deploy:
    # needs: run-tfscan  # Ensure tfscan must pass first
    uses: ./.github/workflows/deployment.yml
    with:
      workingDirectory: .
    secrets:
      client-id: ${{ secrets.AZURE_AD_CLIENT_ID }}
      tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
