name: "Terraform Deployment"

on:
  workflow_call:
    inputs:
      workingDirectory:
        description: "Working directory for Terraform commands"
        required: true
        type: string
    secrets:
      client-id:
        required: true
      tenant-id:
        required: true
      subscription-id:
        required: true

permissions:
  contents: write
  id-token: write

jobs:
  terraform:
    name: 'Terraform'
    env:
      client-id: ${{ secrets.client-id}}
      tenant-id: ${{ secrets.tenant-id}}
      subscription-id: ${{ secrets.subscription-id}}
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
          
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Install Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '>= 1.9, < 2.0.0' # Use the latest stable version

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.client-id}}
          tenant-id: ${{ secrets.tenant-id}}
          subscription-id: ${{ secrets.subscription-id}}
          auth-type: SERVICE_PRINCIPAL

      - name: Initialize Terraform
        run: terraform init
        working-directory: ${{ inputs.workingDirectory }}

      # - name: Terraform Plan
      #   run: terraform plan -var="subscription_id=${{ secrets.subscription-id }}" -var="tenant_id=${{ secrets.tenant-id }}"
      #   working-directory: ${{ inputs.workingDirectory }}

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve -var="subscription_id=${{ secrets.subscription-id }}" -var="tenant_id=${{ secrets.tenant-id }}" 
      #   working-directory: ${{ inputs.workingDirectory }}

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var="subscription_id=${{ secrets.subscription-id }}" -var="tenant_id=${{ secrets.tenant-id }}" 
        working-directory: ${{ inputs.workingDirectory }}
