name: Terraform Format Check

on:
  workflow_call:
    inputs:
      workingDirectory:
        description: "Working Directory"
        required: false
        default: "modules/resourcegroup"
        type: string

jobs:
  tf_fmt_check:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        run: |
          TF_VERSION="1.7.2"
          curl -LO https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
          unzip -o terraform_${TF_VERSION}_linux_amd64.zip
          ls -la /usr/local/bin/
          sudo mv terraform /usr/local/bin/
          sudo chmod +x /usr/local/bin/terraform
          ls -la /usr/local/bin/terraform
          terraform version

      - name: Initialize Terraform
        run: terraform init
        working-directory: ${{ inputs.workingDirectory }}

      - name: Validate Terraform Code
        run: terraform validate
        working-directory: ${{ inputs.workingDirectory }}

      - name: Run Terraform Format Check
        run: terraform fmt -list=true -write=false -diff=true -check=true -recursive
        working-directory: ${{ inputs.workingDirectory }}
