name: Terraform Lint Check

on:
  workflow_call:
    inputs:
      workingDirectory:
        description: "Working Directory"
        required: false
        default: "."
        type: string

jobs:
  tf_lint_check:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Initialize TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint --chdir=${{ inputs.workingDirectory }}
