name: Terraform Quality Scan

on:
  workflow_call:
    inputs:
      workingDirectory:
        description: "Working directory for Terraform commands"
        required: true
        type: string
      runTfFmt:
        description: "Run terraform fmt"
        required: false
        type: boolean
        default: true
      runTfSec:
        description: "Run tfsec scan"
        required: false
        type: boolean
        default: true
      runTfLint:
        description: "Run tflint"
        required: false
        type: boolean
        default: true
      runTfDocs:
        description: "Run terraform-docs"
        required: false
        type: boolean
        default: true
      runCheckov:
        description: "Run Checkov scan"
        required: false
        type: boolean
        default: true
      runSuperLinter:
        description: "Run Super Linter"
        required: false
        type: boolean
        default: true
      runFolderLint:
        description: "Run Folder Structure Linter"
        required: false
        type: boolean
        default: true
      runVersionLint:
        description: "Run Terraform version lint"
        required: false
        type: boolean
        default: true

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - name: Checkout qualityframework repository
        uses: actions/checkout@v4
        with:
          path: qualityframework

      - name: Debug - Check file paths
        run: |
          echo "Current Directory:"
          pwd
          echo "Files in repo:"
          ls -R

  terraform-format-check:
    if: ${{ inputs.runTfFmt }}
    uses: ./.github/workflows/tffmt.yml
    with:
      workingDirectory: ${{ inputs.workingDirectory }}

  terraform-security-scan:
    if: ${{ inputs.runTfSec }}
    uses: ./.github/workflows/tfsec.yml
    with:
      workingDirectory: ${{ inputs.workingDirectory }}

  terraform-lint:
    if: ${{ inputs.runTfLint }}
    uses: ./.github/workflows/tflint.yml
    with:
      workingDirectory: ${{ inputs.workingDirectory }}

  terraform-docs:
    if: ${{ inputs.runTfDocs }}
    uses: ./.github/workflows/tfdocs.yml
    with:
      workingDirectory: ${{ inputs.workingDirectory }}

  checkov:
    if: ${{ inputs.runCheckov }}
    uses: ./.github/workflows/checkov.yml
    with:
      workingDirectory: ${{ inputs.workingDirectory }}

  superlinter:
    if: ${{ inputs.runSuperLinter }}
    uses: ./.github/workflows/superlinter.yml
    with:
      workingDirectory: ${{ inputs.workingDirectory }}

  folder-structure-lint:
    if: ${{ inputs.runFolderLint }}
    uses: ./.github/workflows/folderslint.yml
    with:
      workingDirectory: ${{ inputs.workingDirectory }}

  terraform-version-lint:
    if: ${{ inputs.runVersionLint }}
    uses: ./.github/workflows/versionlint.yml
    with:
      workingDirectory: modules/resourcegroup
